### ISSUE TITLE
Support VitePress-like diff/highlight/focus notation

### ISSUE THREAD

**Issue by antfu** [nuxt-modules/mdc#114]
https://vitepress.dev/guide/markdown#line-highlighting-in-code-blocks

Since VitePress is also using Shikiji and I extracted those notions into a separate package: https://shikiji.netlify.app/packages/transformers

To support them in MDC, it should be straightforward to install those transformers in Shkiji and add a few CSS to style them. 

Request raised by @jd-solanki in Discord: https://discord.com/channels/937808017016119440/1185770572391665714/1186282233397518386

WDYT /cc @farnabaz @Atinux?

**Comment by Atinux** [comment]
It would be great to support this yes, happy to take a stab at it @antfu ?
