### ISSUE TITLE
Nuxt 3.9: WARN  Failed to resolve dependency: is-buffer, present in 'optimizeDeps.include'

### ISSUE THREAD

**Issue by bernhardberger** [nuxt-modules/mdc#121]
https://github.com/nuxt-modules/mdc/blob/main/src/module.ts#L56

`is-buffer` is not in the package.json as dependency. This crashes the dev-server in Nuxt 3.9.

See:
https://github.com/nuxt/nuxt/issues/24927

If I remove the `nuxt-buffer` from `module.mjs`'s optimize deps the dev-server runs and doesn't crash anymore.

**Comment by PatrikBird** [comment]
The official example on [Stackblitz](https://stackblitz.com/github/nuxt/content/tree/main/examples/essentials/hello-world?file=app.vue) logs the warning, too (using the current latest tags: **nuxt 3.9.1** and **content 2.10**):
>  WARN  Failed to resolve dependency: is-buffer, present in 'optimizeDeps.include'

The dev server does not crash there but logs another warning:
> [Vue warn]: Failed to resolve component: NuxtExampleLayout 
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
