### ISSUE TITLE
Proposal: Support `mdc.config.ts` file

### ISSUE THREAD

**Issue by antfu** [nuxt-modules/mdc#124]
Different from build-based tools like VitePress, one benefit of Nuxt Content/Nuxt MDC is that the rendering could happen on the build/server/client sides isomorphicly for dynamic content. However, with the current approach, the capability of customization is quite limited and not taking full advantage of integrations like `rehype`, `remark` and `shikiji.` 

For example, according to https://content.nuxt.com/get-started/configuration#markdown, to add custom retype/remark plugins, we use a static map/array to define the package name and options. This is limited to only the plugins that have been published to npm, and make it hard to add inline ad-hoc plugins, or high-order plugins. Similar situation applies to Shikiji, where we don't provide options for adding custom transformers.

The limitation coming from the `nuxt.confg.ts` is at built-time, and it's almost impossible to serialize functions and JS closures into the runtime context. Thus, I propose that we introduce a new `mdc.config.ts` file that is intended to be imported by both the client and server sides, similar to `app.config.ts` - so that users could provide customization in a much more interactive way.

For example:

```ts
// mdc.config.ts
import { defineConfig } from '@nuxtjs/mdc/config'
import rehypeDocument from 'rehype-document'
import rehypeFormat from 'rehype-format'
import rehypeRaw from 'rehype-raw'
import rehypeStringify from 'rehype-stringify'
import remarkParse from 'remark-parse'
import remarkRehype from 'remark-rehype'
import { transformerNotationDiff } from 'shikiji-transformers'

export default defineConfig({
  rehypePlugins: [
    rehypeDocument,
    rehypeForma,
	() => {
       // custom inline plugins
    }
  ],

  remarkPlugins: [
    remarkRehype,
    // ...
  ]

  highlight: async (code, lang) => {
    // custom highlight function
  },

  // or configure as an option with the default highlighter
  highlight: {
    shikiji: {
      transformers: [
        transformerNotationDiff(),
      ]
    }
  }
})
```

And multiple `mdc.config.ts` might be able to be provided via other modules by hooks,

```ts
nuxt.hook('mdc:config-sources', files => {
	files.push('./my-custom-mdc-extension.ts')
})
```

This would allow for integrating features like twoslash #120, provided by a separate module, without everybody paying the dependencies sizes.

**Comment by Atinux** [comment]
I really like the idea and understand the issue of the nuxt.config!

I am good why that, ok for you too @farnabaz ?

**Comment by farnabaz** [comment]
I like it, this resolve our long-lasting issue with custom remark/rehype plugins 🚀 👍

**Comment by antfu** [comment]
Thanks! I will try to get work on it
