### ISSUE TITLE
Typescript error when using with storybook nuxt

### ISSUE THREAD

**Issue by bahulneel** [nuxt-modules/mdc#149]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@nuxtjs/mdc@0.5.0` for the project I'm working on.

When using mdc sith storybook-nuxt, the compiler complains of some type mismatch. To fix it, I updated the props to match the type signature.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue b/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue
index d959982..ca94de6 100644
--- a/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue
+++ b/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue
@@ -1,22 +1,16 @@
 <template>
-  <NuxtLink
-    :href="href"
-    :target="target"
-  >
+  <NuxtLink :href="href" :target="target">
     <slot />
   </NuxtLink>
 </template>
 
 <script setup lang="ts">
-defineProps({
-  href: {
-    type: String,
-    default: ''
-  },
-  target: {
-    type: String,
-    default: undefined,
-    required: false
-  }
+export interface Props {
+  href: string
+  target?: '_blank' | '_parent' | '_self' | '_top' | (string & object) | null
+}
+
+withDefaults(defineProps<Props>(), {
+  href: ''
 })
 </script>
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by farnabaz** [comment]
This should be fixed in https://github.com/nuxt-modules/mdc/commit/6acc231d7607e4844e7aac6039d7d5042d690352. Will be released in next patch. 👍
