### ISSUE TITLE
Compile markdown inside a markdown ?

### ISSUE THREAD

**Issue by cnicodeme** [nuxt-modules/mdc#150]
Hi !

I have a markdown content that explains some data on my API, and I want to show some code related example on the page.
But each page shows only one specific language, that is defined in the URL (like /guides/python/xxx)

So in pages/guides, I have [slug].vue:

```vue
<template>
    <div>
        <ContentRenderer :value="data">
            <h1>{{ data.title }}</h1>
            <ContentRendererMarkdown :value="data" />
        </ContentRenderer>
    </div>
</template>

<script setup>
const route = useRoute()
const { data } = await useAsyncData('page-data', () => queryContent(`/guides/${route.params.slug}`).findOne())
</script>
```

In content, I have, for instance, something like:

`guides/how-to-create-an-account.md`:

```
It's easy to create an account, you need to send a POST request to https://api.example.com/account/ with your name and email.

Here's a code sample in {{ language }}:

<ContentDoc :path="`/guides/_code/${language}/${slug}`" />
```

The idea in the last file is to have access at some variables (language, slug) and re-use the `ContentDoc` component to load the code and compile it and add it back.

Is there a way to achieve that?

(I can't use tabs in the code like in API Documentation, as each articles is writen for a specific language).

Thanks !

**Comment by farnabaz** [comment]
You can create a custom component to fetch and render the content, and use that component inside your guide page. Lets say you named your component `CodeSample`

```
It's easy to create an account, you need to send a POST request to https://api.example.com/account/ with your name and email.

Here's a code sample in {{ language }}:

:code-sample{:language="language" :slug="slug"}
```

**Comment by cnicodeme** [comment]
Sorry I'm following up on this, but how can you make a custom element that span over multiple lines?
Do you have some documentation for this? I couldn't find anything on https://content.nuxt.com/

Thank you :)
