### ISSUE TITLE
Line breaks don't works properly

### ISSUE THREAD

**Issue by jeannen** [nuxt-modules/mdc#151]
Hi!

I tried to use the MDC component, but when I do line breaks they don't render as expected

- One line break = Nothing
- Two line breaks = One line break (create a new `<p>`)
- More than two line breaks = Nothing (act like if there was only two)

Reproduction:
```vue
<template>
    <div>
        <MDC :value="markdown" tag="article" class="md-article" />
        <textarea v-model="markdown" rows="10" cols="100" @keydown.cmd.b.prevent="boldText" @keydown.ctrl.b.prevent="boldText"></textarea>
    </div>
</template>

<script setup>
    const markdown = ref(`# Hello, world!\n## All good?\n\n\n\n\n I am a markdown string. And **I am bold**.And *I am italic*. And ***I am bold and italic***. \n\nAnd [I am a link](https://www.google.com).\n\nAnd I am a list:\n\n - Item 1\n - Item 2\n - Item 3\n - Item 4\n\nAnd I am a code block:\n\`\`\`javascript\nconsole.log('Hello, world!');\n\`\`\`\n\nAnd I am a blockquote:\n> Hello, world!`);
</script>


```

**Comment by luke-z** [comment]
I encountered this problem today as well and solved it by using the "remark-breaks" plugin.

I just added it to the nuxt.config.ts file in the mdc config.

```
mdc: {
   remarkPlugins: {
      'remark-breaks': {},
   },
   ...
```

Just make sure to add the plugin to your package.json :)

Maybe it can help you somehow haha

**Comment by jeannen** [comment]
Ended up solving it by adding a margin after the p elements inside the generated HTML, only works for one max (so you can't have multiple line breaks) but that does it for now
 
'''vue
<MDC class="foo".../>
<style>
    .foo {
        p {
            margin-bottom: 10px;
        }
}
'''

**Comment by farnabaz** [comment]
If you want to have multiple line breaks, you can use `<br>` tag or equivalent `:br` in MDC.

By default, multiple line breaks ignore in Markdown. Checkout [Markdown syntax](https://www.markdownguide.org/basic-syntax/#line-breaks)

**Comment by jeannen** [comment]
> I encountered this problem today as well and solved it by using the "remark-breaks" plugin.
> 
> I just added it to the nuxt.config.ts file in the mdc config.
> 
> ```
> mdc: {
>    remarkPlugins: {
>       'remark-breaks': {},
>    },
>    ...
> ```
> 
> Just make sure to add the plugin to your package.json :)
> 
> Maybe it can help you somehow haha

A bit annoying to have to download a plugin for this tho 🥲



> If you want to have multiple line breaks, you can use `<br>` tag or equivalent `:br` in MDC.
> 
> By default, multiple line breaks ignore in Markdown. Checkout [Markdown syntax](https://www.markdownguide.org/basic-syntax/#line-breaks)


Is there a way to change the default settings? Without external package/modules
