### ISSUE TITLE
Can't run project in CodeSandbox and Local. Could not compile template mdc-highlighter.mjs | No highlighter specified.

### ISSUE THREAD

**Issue by lnbiuc** [nuxt-modules/mdc#157]
When I clicked on CodeSandbox in README.md, an error occurred and the playground could not run.

![image](https://github.com/nuxt-modules/mdc/assets/85148161/e297608f-2c17-488f-9a8d-9d48d0657699)

So I cloned the project to my local machine, but the same error still occurred.

<img width="1214" alt="image" src="https://github.com/nuxt-modules/mdc/assets/85148161/a86ef442-d118-475e-a633-ff81560e773e">

<img width="1214" alt="image" src="https://github.com/nuxt-modules/mdc/assets/85148161/05b981ac-8fb0-42ce-9e8b-d1b382295e5a">

The same error occurred in my project when I tried to use the highlighter.

<img width="1214" alt="image" src="https://github.com/nuxt-modules/mdc/assets/85148161/2eeeb708-7dfc-489e-a6fa-6ebf9bfe2020">

```js
export default defineNuxtConfig({
	modules: [
		'@nuxtjs/mdc',
	],


mdc: {
		headings: {
			anchorLinks: {
				h1: true,
				h2: true,
			},
		},
		highlight: {
			highlighter: 'shiki',
			theme: {
				default: 'github-light',
				dark: 'github-dark',
			},
			preload: [
				'json',
				'yaml',
				'toml',
				'bash',
				'sh',
				'shell',
				'console',
				'plaintext',
				'java',
			],
		},
	},

})
```

I tried to use on the server side.

```js
// @ts-expect-error miss type
import { parseMarkdown } from '@nuxtjs/mdc/runtime';

export async function render(source: string) {
	return await parseMarkdown(source.replace(/\\n/g, '\n'));
}

```

Thank you very much for your help.

**Comment by farnabaz** [comment]
Thanks for the issue @lnbiuc,
Seems that CodeSandbox playground have some issue with Vite version.
Everything works fine in local and StackBlitz. I replaced playground link with StackBlitz until we resolve the issue in CodeSandbox.

You can play with module here: https://stackblitz.com/github/nuxt-modules/mdc?file=playground%2Fapp.vue

I'm closing this issue but I'll dig the issue.
