### ISSUE TITLE
Prose Components not working as expected.

### ISSUE THREAD

**Issue by robinkloeckner** [nuxt-modules/mdc#175]
Hi everyone. I want to render MarkDown which contains code blocks. The code blocks should contain additional features (such as a copy button or displaying the file format). Therefore I tried to "extend" the `<ProsePre>` component / used a "custom Prose component" but either it is not working or the documentation is missing some information on how to work with Prose components.

**Setup**
mdc: 0.6.1
nuxt: 3.11.1
vue: 3.4.21 

**What I did**
Starting with the following component:

```
<script setup>
const md = '# Hello MDC\n'+
'```js\nconst x = 1;\n```';
</script>

<template>
  <MDC :value="md" />
</template>
```

The rendered output is:
 
```
 <div class="">
  <h1 id="hello-mdc">
     <!--[-->
     Hello MDC
     <!--]-->
   </h1>
   <pre class="language-js">
     <!--[-->
     <code>
       const x = 1;
     </code>
     <!--]-->
   </pre>
</div>
```

That is the case for both Nuxt configurations, `mdc.components.prose: true` and `mdc.components.prose: false`. The `<pre>` tag is taking the full width available. In the development mode, I can see the `data-v-inspector` being linked to the `<ProsePre>` component inside the `node_modules` folder when `mdc.components.prose: true`.

Now, the documentation is not precisely indicating on how to add extra features so I started with setting `mdc.components.prose: true`, added a `ProsePre.vue` component under `components/`, copied the source code from the `<ProsePre>` default component and added extra code. However, my changes did not apply, even if just adding a console log and leaving the remaining code unchanged. Instead the `<pre>` tag in the rendered output no longer takes the full width available but instead takes the width of its content.

Renaming my `ProsePre.vue` component to `CustomPre.vue` with the following Nuxt mdc configuration still does not work.

```
  mdc: {
    components: {
      prose: false,
      map: {
        pre: 'CustomPre',
      }
    }
  }
```

The rendered output:

```
<div class="">
  <h1 id="hello-mdc">Hello MDC</h1>
  <CustomPre class="language-js" code="const x = 1;" language="js" meta>
    <code>
      const x = 1;
    </code>
  </CustomPre>
</div>
```

However, in both cases there seems to be a mapping to the Prose component since the language (js) is added as a suffix to the class value `language-js`.

**Additional information**
In my terminal I get the following warning when working with Prose components:

``` 
 WARN  Cannot stringify arbitrary non-POJOs ObjectRefImpl
 WARN  Cannot stringify arbitrary non-POJOs RefImpl
 WARN  Cannot stringify a function 
```

as well as several warnings because of missing source maps.

**Expected behavior**
Adding a `ProsePre.vue` component under `components/`, defining the same props as in the [MDC source code](https://github.com/nuxt-modules/mdc/blob/main/src/runtime/components/prose/ProsePre.vue) and adding additional code. This component is then rendered instead of the default `<ProsePre>`component.

**Question**
How do I properly extend a Prose component (getting access to the props and adding extra code) and render them in valid HTML5?

**Comment by robinkloeckner** [comment]
I found that Prose components inside `components/` must to be globally registered. Maybe it is helpful to note it in the documentation under [Prose Components](https://github.com/nuxt-modules/mdc?tab=readme-ov-file#prose-components).

**Comment by soylomass** [comment]
@robinkloeckner How did you solve this? I'm trying both by creating a ProseCode.vue file in components/global and by nuxt.config, but can't replace the ProseCode component.

**Comment by soylomass** [comment]
Looks like ProseCode can't be replaced. Tried replacing ProsePre (which encloses <code>) and it worked.

**Comment by robinkloeckner** [comment]
I had to register them globally to be resolved. In my case I created a subdirectory for my prose components to separate them from the remaining components `components/prose/`. Next, I registered them globally with the following `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  modules: ['@nuxtjs/mdc'],
  mdc: {
    components: {
      prose: true
    }
  },
  components: {
    global: true,
    path: './components/prose'
  }
})
```

Inside `components/prose/` I created `ProsePre.vue` and with the source code from the initial `<ProsePre>`component.

**Comment by yarin-zhang** [comment]
@robinkloeckner Your method is effective for me, and I suggest that MDC should add it to the document - if this is a recommended practice.

**Comment by robinkloeckner** [comment]
@yarin-zhang I've been facing resolving issues with this method with regard to the remaining components inside `components/`. Alternatively you can substitute the `components: {...}` part from `nuxt.config.ts` by adding the `.global` suffix to your Prose components name, e.g. `ProsePre.vue` -> `ProsePre.global.vue`

**Comment by igor9silva** [comment]
This should **definitely** be on the README.

**Comment by TNXG** [comment]
However, this seems to make TailwindCSS and the component libraries that depend on it unusable?
