### ISSUE TITLE
Incorrect pnpm install

### ISSUE THREAD

**Issue by Dino-Kupinic** [nuxt-modules/mdc#184]
It is said one should use
```
# Using pnpm
pnpm add --dev @nuxtjs/mdc
```
But this does not work and throws this error:
<img width="253" alt="image" src="https://github.com/nuxt-modules/mdc/assets/87943435/91432a8c-72f3-4572-a267-51909e914b50">
Instead it should be
`pnpm add -D @nuxtjs/mdc`

**Comment by farnabaz** [comment]
Thanks for the issue, This is not related now since we suggest using `nuxi module add` command in docs.
