### ISSUE TITLE
Doublon in shiki languages

### ISSUE THREAD

**Issue by ManUtopiK** [nuxt-modules/mdc#194]
https://github.com/nuxt-modules/mdc/blob/f5ee5a5ad3f5cae3e4e2014fc9c625477ca458c1/src/module.ts#L17

https://github.com/nuxt-modules/mdc/blob/f5ee5a5ad3f5cae3e4e2014fc9c625477ca458c1/src/module.ts#L20

**Comment by farnabaz** [comment]
Thanks for the issue. Fixed in https://github.com/nuxt-modules/mdc/pull/201
