### ISSUE TITLE
Add option to disable all `headings.anchorLinks` at once

### ISSUE THREAD

**Issue by stefanobartoletti** [nuxt-modules/mdc#203]
Currently, the default behavior when rendering headings inside a markdown content is to use anchor links on several heading levels.

In the scenario where one needs to disable anchor links on all levels, currently the config object to pass is like that

```js
  // nuxt.config.js
  mdc: {
    headings: {
      anchorLinks: {
        h1: false,
        h2: false,
        h3: false,
        h4: false,
        h5: false,
        h6: false,
      },
    },
  },  
```

This is quite verbose, and, even if I don't have numbers to support this, my guess is that it is more common to be in need to disable links on all levels, rather than in some of them.

I'd like to have an option to disable all of them at once in addition to the current granular setting, maybe like this:

```js
  // nuxt.config.js
  mdc: {
    headings: {
      anchorLinks: false
    },
  },  
```

Thanks :v:

**Comment by stefanobartoletti** [comment]
It *seems* to work on the site frontend without any noticeable problem, but I have an typescript error thrown in `nuxt.config.js`, if I set it to `false`:

![Screenshot_20240515_170840](https://github.com/nuxt-modules/mdc/assets/36746429/58a8df36-d34b-4b14-a73c-74a794538a6e)

**Comment by nobkd** [comment]
Yeah. `false` (or `boolean`) needs to be represented as type for `heading.anchorLinks` in https://github.com/nuxt-modules/mdc/blob/main/src/types.ts

---

But probably also needs changes for `true` if one wants to activate all anchor links at once.

:shrug:

**Comment by stefanobartoletti** [comment]
Thanks for your reply @nobkd, I guess I can ignore typescript warnings for now.

I can open a PR to add `false` as a valid type if it is helpful, but for adding more logic even for `true` at the moment I'm not knowledgeable enough of the module's inner workings to provide a good solution.

Let me know if a PR for `false` only could be nice.

**Comment by farnabaz** [comment]
Having `true` and `false` to enable and disable all links would be nice IMO

> but for adding more logic even for true at the moment I'm not knowledgeable enough of the module's inner workings to provide a good solution.

To handle `true` we can check `options.headings.anchorLinks` before passing to `runtimeConfig` and generate proper object syntax if necessary
https://github.com/nuxt-modules/mdc/blob/fade64f0b505e5c4a13237f8425858decaff18b1/src/module.ts#L62

**Comment by stefanobartoletti** [comment]
Thanks @farnabaz, would you accept two separate PR's?

I can prepare a quick one for `false` in a breeze, and properly implement `true` when I have the chance to see how it is working.

**Comment by farnabaz** [comment]
Sure, feel free to open two different PRs
