### ISSUE TITLE
Custom prose img components will cause hydration mismatch

### ISSUE THREAD

**Issue by enpitsuLin** [nuxt-modules/mdc#212]
I try override prose component `<ProseImg/>` to show caption under image in nuxt/content template, but got hydration mismatch warning, I thought it was cause by content module(nuxt/content#2640), but this issue also be found in MDC playground

I just add `<figure/>` and `<figurecaption/>`, after several try that I realized if there are some unexpected element wrap it would cause hydration mismatch, but cant resolve it

<img width="1440" alt="image" src="https://github.com/nuxt-modules/mdc/assets/29378026/f02c2f4a-88a0-4490-8a3b-d36c15b3bf85">

**Reproduction**

https://stackblitz.com/edit/github-1szhfr

**Comment by enpitsuLin** [comment]
Just figured out the `<figure/>` is block element cant be placed in the paragraph or those elements which not flow elements

**Comment by stared** [comment]
@enpitsuLin How did you solve this one?

Markdown parser automatically wraps things in paragraphs.
