### ISSUE TITLE
Type exports broken 0.8.1

### ISSUE THREAD

**Issue by adamdehaven** [nuxt-modules/mdc#225]
It looks like the changes in https://github.com/nuxt-modules/mdc/pull/223 broke the type exports from everything under the `/dist/runtime/` directory.

After a build, `/dist/runtime/index.d.ts` is attempting to export `parseMarkdown` and `createMarkdownParser` from `/dist/runtime/parser.js` which no longer exists in the `dist` bundle. It looks like the export should be from `/dist/runtime/parser/index.js`. **The functions do appear to work in a host app**.

There are other type exports missing as well (not available from the root or a subdirectory) including `MDCParserResult`.

I'd recommend running the build and inspecting the files in the `/dist/*` folder.

#223 does resolve the `nuxt.config.ts` `ModuleOptions` bug though 🎉 

## Reproduction

[Code Sandbox reproduction](https://codesandbox.io/p/github/adamdehaven/mdc-wasm-repro/draft/lucid-merkle)

Once the dependencies are installed, you can run `pnpm typecheck` to see the error from `MDCParserResult` not being exported/available.

**Comment by farnabaz** [comment]
I can't access to the sandbox, seems private

**Comment by adamdehaven** [comment]
@farnabaz sorry about that; pushed the files to here: https://github.com/adamdehaven/mdc-repros
