### ISSUE TITLE
How to display a table?

### ISSUE THREAD

**Issue by Pfenya** [nuxt-modules/mdc#231]
Hi,

I am trying to define some markdown content in a component to pass it to a child component for rendering (using markdown because the child is re-used and uses markdown in other cases).
The information I am trying to pass should be displayed as a table but I cannot get it to render it as a table. I can either get it to render the information as simple text or I can get it to render as code but not as a table.

The list of Prose Components has a ProseTable so I assume I am simply missing something to make this work.

My very condensed test case:

``` const mdc = `|  table | test |  \n | 1 | 2 |` ```
``` const  techOutTest = `|  table | test |
      | 1 | 2 |` ``` (with two lines)
```const ast =  await  parseMarkdown(mdc);```

`<MDCRenderer v-if="ast?.body" :body="ast.body" :data="ast.data" />`
`<MDC v-if="techOutTest" :value="techOutTest" tag="div" class="" />`

I have one remarkPlugin configured if that makes a difference: remark-breaks

I have tried several different syntaxes for the markdown but nothing I have tried so far has gotten it to output it as a table. Any help would be greatly appreciated!

**Comment by nobkd** [comment]
Try using the verbose Markdown syntax for tables

```diff
- const mdc = `| table | test | \n | 1 | 2 |`
+ const mdc = `| table | test | \n |-|-| \n | 1 | 2 |`
```

```md
| table | test |
| ----- | ---- |
|   1   |   2  |
```

**Comment by Pfenya** [comment]
Thank you! This works - i was sure i had tested that as well but apparently I hadn't (or incorrectly)
