### ISSUE TITLE
Generated markdown AST is wrong for bold text in tables

### ISSUE THREAD

**Issue by larbish** [nuxt-modules/mdc#247]
This markdown:
![Screenshot 2024-08-12 at 14 14 33](https://github.com/user-attachments/assets/53cfe17e-6cc5-4a92-95fb-9bcd0c396b3d)

is generating this node:
![Screenshot 2024-08-12 at 14 14 25](https://github.com/user-attachments/assets/c1e8ec2d-c6f2-4527-8aee-b1ec05580865)

Everything coming after the bold syntax is outside of the `p` node

**Comment by farnabaz** [comment]
Seems that this happens outside the mdc module's scope and maybe in wrapper functions

<img width="1438" alt="Screenshot 2024-09-12 at 12 05 32" src="https://github.com/user-attachments/assets/81ce3023-8daf-4de9-80a2-2b171e848d23">
