### ISSUE TITLE
Pre-transform error: Failed to resolve import "#build/mdc-image-component.mjs"

### ISSUE THREAD

**Issue by mithindev** [nuxt-modules/mdc#271]
The `ProseImg.vue` component located in `node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue` is unable to resolve some dependencies.

![Error Screenshot](https://github.com/user-attachments/assets/34754f83-3000-46f8-a429-e23f17f9522f)

I am encountering the following error:

`4:43:55 PM [vite] Pre-transform error: Failed to resolve import "#build/mdc-image-component.mjs" from "node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue". Does the file exist?`

**Comment by farnabaz** [comment]
Do you mind providing a simple reproduction? It couldn't reproduce the issue
