### ISSUE TITLE
export `processor` and new `parseAst` utility

### ISSUE THREAD

**Issue by sandros94** [nuxt-modules/mdc#285]
I've been using more and more remark lately, but most importantly I've been taking advantage of mdast to programmatically modify it and then go back to markdown. But every time I comeback to this module it feels too much limited in a single direction (md -> custom-ast).

While studying the possibility to draft a PR for a `parseAst` I've also noticed that the [processor itself isn't exported](https://github.com/nuxt-modules/mdc/blob/0fd67f95404df07933364838946202906340af7e/src/runtime/parser/index.ts#L58), preventing any reuse of the processor and all the loaded plugins and configs.

Once the processor is exported it is a matter of reversing the [current compiler](https://github.com/nuxt-modules/mdc/blob/0fd67f95404df07933364838946202906340af7e/src/runtime/parser/compiler.ts) and outputting a markdown string.

**Comment by sandros94** [comment]
For the processor this could be easily achievable without breaking changes by renaming the current `createMarkdownParser` to `createProcessor` but changing its return to both `processor` and `parser` (the current return), and then add:

```ts
export const createMarkdownParser = async (inlineOptions: MDCParseOptions = {}) => (await createProcessor(inlineOptions)).parser
```

or am I offtrack?

**Comment by farnabaz** [comment]
I like the idea of exporting processor to help with markdown generation.

**Comment by sandros94** [comment]
@farnabaz would you like me to draft the `createProcessor` util as I've described? Or do you have a different approach in mind?

**Comment by farnabaz** [comment]
Your suggestion looks good to me 👍 
Looking forward to seeing your PR 🙂

**Comment by sandros94** [comment]
Once it gets released I'll start experimenting for a `parseAst` util
