### ISSUE TITLE
MDC break when using `\` inside a non-v-binded prop

### ISSUE THREAD

**Issue by L33Z22L11** [nuxt-modules/mdc#296]
To reprodruce:

```mdc
:copy{code="D:\Software\"}
```

Outputs AST:

```json
[
    {
        "type": "element",
        "tag": "copy",
        "props": {},
        "children": []
    },
    {
        "type": "text",
        "value": "{code=\"D:\\Software\"}"
    }
]
```

But what is expected:

```json
[
    {
        "type": "element",
        "tag": "copy",
        "props": {
            "code": "D:\\Software\\"
        },
        "children": []
    }
]
```

Maybe related to #273.

**Comment by farnabaz** [comment]
Sorry for bringing breaking changes to the patch version, this was unwanted.
But The previous behavior was wrong, attribute values are quotes, and the parser should check for escaped characters.

Using `:copy{code="D:\\Software\\"}` should solve the problem.

**Comment by L33Z22L11** [comment]
Thank you for your response and explanation! I understand the intention behind the change and the need to handle escaped characters correctly in attribute values. However, I believe there is a case for distinguishing between `v-bind` props and regular MDC props for consistency with how HTML handles attributes.

For example, `v-bind` props (e.g., `:foo{:test='{"foo":"I\'d love to}'}')` are inherently JavaScript expressions and should follow the escaping rules introduced in this patch. Regular MDC props or attributes, on the other hand, should align with the way HTML treats attribute values—without escaping backslashes.

Would it be feasible to apply the new escaping logic only to `v-bind` props (with the colon prefix) while leaving regular MDC props unaffected? This approach could preserve both compatibility and expected behavior for developers familiar with HTML attribute handling.
