### ISSUE TITLE
How to load a .md or .mdx file from within a folder in my nuxt or vue app ?

### ISSUE THREAD

**Issue by Mikaleb** [nuxt-modules/mdc#302]
All example i see are written like this : 

```
<script setup lang="ts">
const md = `
::alert
Hello MDC
::
`
</script>
```

but how do you do an import like 
``` 
const file = import (content/`${slug}.mdx) 
```

?

**Comment by farnabaz** [comment]
For that, you need to use [Nuxt Content](https://github.com/nuxt/content/). 
Checkout docs https://content.nuxt.com/

**Comment by Mikaleb** [comment]
What if i use the Vue implementation ?

**Comment by farnabaz** [comment]
In Vue project, you can use raw import to get the markdown content and pass it to `<MDC>` component

```ts
import markdownFile from './example.md?raw'; // Use raw loader in Vite/Webpack
```

**Comment by Mikaleb** [comment]
Which doesn't work natively in a fresh install of vue for any mdx file : 

```[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.```

Neither for md : 

```
Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .md file format, or if it's an asset, add "**/*.md" to `assetsInclude` in your configuration.
```

**Comment by farnabaz** [comment]
Checkout Vite's raw-loader https://www.npmjs.com/package/vite-raw-plugin

**Comment by Mikaleb** [comment]
It works ! Thanks a lot, I made my own with a few tweaks for mdx but yeah it works well ! [vite-mdx-raw-plugin](https://github.com/Mikaleb/vite-mdx-raw-plugin)
