### ISSUE TITLE
[Feature Request] Evaluate MDCData when used as YAML frontmatter or prop data

### ISSUE THREAD

**Issue by adamdehaven** [nuxt-modules/mdc#308]
MDC allows for binding data in markdown (e.g. via frontmatter and MDC props) and utilizing that data within the raw markdown:

```mdc
---
title: "My Page"
customVariable: "better than cats"
---

# {{ $doc.title }}

Dogs are {{ $doc.customVariable || 'the best' }}.
```

It would be great if you could _also_ utilize this data (essentially any property of `MDCData` stored as a child property of `$doc`) within frontmatter and MDC block/inline component props. (This should also include custom `data` passed into the MDCRenderer and other components.)

This is somewhat supported if you utilize the `v-bind` syntax with inline components:

```mdc
---
type: "warning"
---

::alert{:type="type"}
Your warning
::
```

However, it would be nice to support this for YAML-defined props as well.

As an example:

```mdc
---
title: "Data binding page"
colors: 
  foo: "#007ac1"
---

::custom-block-component
---
color: {{ $doc.colors.foo || 'blue' }}
---
This is custom component slot content on the {{ $doc.title || 'page' }}.
::
```

In this example:

1. The `custom-block-component` has a prop of `colors: Record<string, string>`
2. The MDCData should be evaluated to its resulting value when passed as a prop value to the MDC block component used within the document, utilizing the `$doc.colors.foo` value if set; otherwise, falling back to the provided default value.

In addition, inside a child MDCRenderer component where it has access to its own data as well as the parent's data (e.g. via Vue's `provide/inject`), it would be ideal to also be able to evaluate MDCData within the child's frontmatter. I'll exclude the example for this now, only to say it means we'd need to evaluate `{{ $doc.foo.bar || 'fallback value' }}` within the frontmatter as well.

---

@farnabaz this would unlock a lot of potential for users to be able to define variables at the top of the page to then configure components further down the page, and would be even more powerful for nested/asynchronous MDCRenderer instances.

Let me know if you need more info, or if you'd like to provide some guidance on how this could be implemented I'm happy to collaborate again 🙌🏼

**Comment by farnabaz** [comment]
It is possible to bind data in YAML props, too, and the syntax is similar to the inline attribute. However, there is no fallback value for props. I don't see a fallback value for props as a necessary feature to support since props in a component could have a default value for themselves.

```ts
---
title: "Data binding page"
colors: 
  foo: "#007ac1"
---

::custom-block-component
---
:color: colors.foo
---
This is custom component slot content on the {{ $doc.title || 'page' }}.
::
```

**Comment by adamdehaven** [comment]
> It is possible to bind data in YAML props, too, and the syntax is similar to the inline attribute.

Ah I see 🚀 

I must have been playing around with setting a _nested_ property, in which case you'd need to define the top-level property with v-bind syntax.

This usage is missing from the Nuxt Content docs; if you're good with it, I'll put up a PR over there?

Thanks again! Resolving this.

**Comment by farnabaz** [comment]
Definitely, looking forward for your PR :)

**Comment by adamdehaven** [comment]
Which branch of the content docs would the PR point to?

**Comment by adamdehaven** [comment]
@farnabaz is it possible to combine a regular string along with a dynamic prop value?

As an example, let's say I wanted to use bound data to construct a URL path:

```mdc
---
slug: "my-page"
---

::custom-link-component
---
:url: "path/to/{{ slug }}"
---
::
```
