### ISSUE TITLE
Not working in Nuxt 3 with ssr: false

### ISSUE THREAD

**Issue by igorjacauna** [nuxt-modules/mdc#314]
StackBlitz - https://stackblitz.com/edit/github-mk7e9kra?file=nuxt.config.ts

Error on console:

```bash
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/debug/src/browser.js?v=669302cd' does not provide an export named 'default' (at create-tokenizer.js:40:8)
```

**Comment by bigiCrab** [comment]
I am using Nuxt 3 with ssr: true and encountering the same issue.

Add optimizeDeps fix my problem.
```js
export default defineNuxtConfig({
  //  ...
  vite: {
    optimizeDeps: {
      include: ["debug"],
    },
  },
)
```

**Comment by aatrooox** [comment]
@bigiCrab you save my life 😱

**Comment by nagsterFVZ** [comment]
Had the same problem with `ssr: true` but seems resolved with the `0.12.0` release for me now.
I've removed the vite optimizeDeps from my config and everything works fine again.

**Comment by igorjacauna** [comment]
Thanks @nagsterFVZ 

The `0.12.0` [resolved](https://stackblitz.com/edit/github-mk7e9kra-y7uhgwhs?file=nuxt.config.ts).

**Comment by thorge** [comment]
I experience the same error with `0.13.0` and `0.13.2`. Has this bug been reintroduced?
