### ISSUE TITLE
Rendering anchor inside of heading tag

### ISSUE THREAD

**Issue by luke-z** [nuxt-modules/mdc#58]
I was just trying out this module to see if I could render the content of a Strapi rich text field.

h1 works well, but for some reason, the h2 and h3 tags have an anchor tag inside.

I used the following sample string: 
```'### h3\n## h2\n# h1\nparagraph'```

It also happens with a simple ```'### h3'```

![image](https://github.com/nuxt-modules/mdc/assets/37207714/718fdc7b-9e5c-4643-9e7e-eca27d43f30c)

**Comment by nobkd** [comment]
You can change this behavior with the [`content.markdown.anchorLinks` option](https://content.nuxt.com/get-started/configuration#markdown).

```ts
// nuxt.config.ts

export default defineNuxtConfig({
  modules: ['@nuxt/content'],

  content: {
    markdown: {
      anchorLinks: false,
    },
  },

  //...
})
```

**Comment by luke-z** [comment]
Oh I see! Didn't know about that option in nuxt content. 
I removed the nuxt content package because it didn't really work for me with the Strapi response. But I guess using it together with this package could turn out pretty handy.

Thanks @nobkd

**Comment by nobkd** [comment]
Not sure, as I have not tested it, but it might also be possible with *only* this package with `mdc.headings` option. See:

https://github.com/nuxt-modules/mdc/blob/264a4d6abef9d66dfb8b30351a55e4a62cf5341b/src/module.ts#L10-L34

It's also possible, that you have to define it for `h2`, `h3`, `h4` separately in the config of this module.

**Comment by luke-z** [comment]
Alright I see, thanks for digging!
Gonna try this out. Makes everything a bit leaner haha

**Comment by nobkd** [comment]
@luke-z
Here are the options for `@nuxt/mdc`:
https://github.com/nuxt-modules/mdc/blob/main/docs/content/0.index.md#configurations

**Comment by luke-z** [comment]
That goes a lot deeper than I expected. Guess I have to look no further 😎

Thank you so much!
