### ISSUE TITLE
[Question] How to add remark/rehype plugin?

### ISSUE THREAD

**Issue by Sun-ZhenXing** [nuxt-modules/mdc#60]
According to the [docs](https://github.com/nuxt-modules/mdc/blob/main/docs/content/0.index.md#configurations), I tried various methods. But none of them work and I would like to know how I can add a plugin directly now.

Here is an example of `remark-math`:

```ts
// nuxt.config.ts
import rehypeKatex from 'rehype-katex'
import remarkMath from 'remark-math'

export default defineNuxtConfig({
  mdc: {
    remarkPlugins: {
      remarkMath,
    },
    rehypePlugins: {
      remarkMath,
    }
  }
})
```
The type also does not match `Record<string, UnistPlugin>`.

**Comment by Sun-ZhenXing** [comment]
Thank you for your help, although this is still problematic.

<img width="288" alt="image" src="https://github.com/nuxt-modules/mdc/assets/44517244/b7a342d8-d951-43bd-a762-38bbf8ba4360">

For example, the type is wrong and block formulas are not rendered. I think this may have nothing to do with MDC though.

**Comment by jonasfroeller** [comment]
I have the same issue with `remark-math` and `rehype-katex` not working in MDC.

**Comment by Sun-ZhenXing** [comment]
@jonasfroeller This issue has been resolved, check out [my answer](https://github.com/nuxt/content/issues/2452#issuecomment-1852028801).
