### ISSUE TITLE
Error when parsing string with backticks in SSR mode

### ISSUE THREAD

**Issue by kedniko** [nuxt-modules/mdc#75]
**Example:**

```vue
<script setup lang="ts">
const notWorkingWithBackticks = `
# Not working
Not working in \`SSR\` mode
`
const working = `
# Working
Nuxt content
`
</script>

<template>
  <div>
    <MDC :value="notWorkingWithBackticks" tag="article" />
    <MDC :value="working" tag="article" />
  </div>
</template>
```

**Console error:**
Invalid prop: type check failed for prop "body". Expected Object, got Undefined 

![image](https://github.com/nuxt-modules/mdc/assets/42846752/c597d9fc-c880-4646-8fb9-e7cf9074138f)

**Comment by farnabaz** [comment]
This is fixed in current version.
Feel free to reopen it or create new one if you see issue persists

**Comment by adamdehaven** [comment]
@farnabaz any idea when this fix will get published to npm?
