### ISSUE TITLE
LaTeX formula support

### ISSUE THREAD

**Issue by Sun-ZhenXing** [nuxt-modules/mdc#89]
I tried to add `remark-math` support, but I got an error when parsing multi-line formulas.

Maybe we still have problems with remark/rehype plugin support. (Maybe it's the parsing order, etc.)

[remark-math#91](https://github.com/remarkjs/remark-math/issues/91).

reproduce: <https://stackblitz.com/edit/nuxt-starter-9lhesd?file=README.md>

Is there a better way to support LaTeX formula?

**Comment by Sun-ZhenXing** [comment]
Refer to: https://github.com/remarkjs/remark-math/issues/91

**Comment by icarusion** [comment]
Hi.

After I configured it, only `$` and `$$` syntax are supported. `(` and `[` syntax cannot be rendered. Has anyone encountered this problem?

```
\(\frac{d}{dx} (\cos x) = -\sin x\)
\(\frac{d}{dx} (\tan x) = \sec^2 x\)
```
