### ISSUE TITLE
Every themes and languages are loaded

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-modules/mdc#92]
Read https://github.com/antfu/shikiji?tab=readme-ov-file#fine-grained-bundle

related to https://github.com/nuxt/content/issues/2422

**Comment by Barbapapazes** [comment]
I'm working on something but this could creata a breaking change since (for me) we do not want to preload any languages.

**Comment by farnabaz** [comment]
This is fixed by moving to new version of Shiki starting [v0.4.0](https://github.com/nuxt-modules/mdc/releases/tag/v0.4.0)
