### ISSUE TITLE
unwrap prop not working

### ISSUE THREAD

**Issue by robsonsobral** [nuxt-modules/mdc#95]
Hi!

I'm using the version 0.2.6 on Nuxt 3.7.3 And can't make the `unwrap` prop to work.

Code sample:

```vue
<!-- eslint-disable-next-line vuejs-accessibility/form-control-has-label -->
<input
  id="natural-person-identification-agreement"
  v-model="naturalPersonIdentificationAgreement"
  type="checkbox"
/>
<MDC
  :value="$t('donationForm.naturalPersonIdentificationAgreement')"
  tag="label"
  unwrap="p"
  for="natural-person-identification-agreement"
/>
```

This code gives me the `p` tag, no `for` parameter and adds an empty `class`!

![image](https://github.com/nuxt-modules/mdc/assets/931642/c2d285c7-19b6-4358-b522-cf2aaa7dbc45)

Am I doing something wrong? Thank you!

**Comment by farnabaz** [comment]
Everything in markdown wraps in a paragraph. 
Currently, there is no standard version to remove the wrapper paragraph directly from MDC module.

**Comment by robsonsobral** [comment]
> Everything in markdown wraps in a paragraph.

This is true

> Currently, there is no standard version to remove the wrapper paragraph directly from MDC module.

MDC shouldn't advertise what it can't do:

> Features
> 
> Mix Markdown syntax with HTML tags or Vue components
> **Unwrap any generated content (ex: `<p>` added by each Markdown paragraph)**
> Use Vue components with named slots
> Support inline components
> Add attributes and classes to inline HTML tags
