### ISSUE TITLE
How can I use the parseMarkdown

### ISSUE THREAD

**Issue by tamanna-makkar** [nuxt-modules/mdc#97]
into the below code. how can I use the AST tree so that it could return markdown content
```
async function main(mdc: string) {
  const {data, body} = await parseMarkdown(mdc)

  // Do your magic with parsed AST tree
  return data
}
```
`<div>{{ main('# hello world') }}</div>` 
for now it is returning me [OBJECT promise], I wanted main function to return the parsed markdown how can I do that ?

**Comment by ManasMadrecha** [comment]
As it is an async function, you can't directly use it in a `template` section as interpolation. 

Rather, for your simple use, you can just use `<MDC>` component which anyway accepts the markdown string and renders the parsed markdown.
